### ISSUE TITLE
Blog post doesn't appear on https://www.open-bio.org/blog/

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#73]
https://www.open-bio.org/2022/01/04/obf-membership-referendum/ can be accessed in various ways (for example, as the Previous post from https://www.open-bio.org/2022/01/20/iscbacademy-webinar-feb-22-yo-yehudi/) but for some reason is not listed on https://www.open-bio.org/blog/ . I checked that it has all the usual categories checked off (including Uncategorized and Blogroll (what even is that?)). I'm mystified.

**Comment by peterjc** [comment]
Not just you seeing this - I do too. I think I noticed earlier, but wrongly assumed it was a caching issue and didn't investigate any further.

**Comment by peterjc** [comment]
It does not look like the tags are important.

Are the ``home-*`` categories relevant?

**Comment by hzahroh** [comment]
Where do you want it to be?

**Comment by nlharris** [comment]
It should be one of the posts shown on https://www.open-bio.org/blog/. They are shown in reverse chronological order, so with a date of 2022/01/04 it should be between the "My virtual participation" and "ISCBacademy" posts.

**Comment by hzahroh** [comment]
This is done too @nlharris @peterjc 
<img width="1092" alt="Screenshot 2022-03-16 at 11 12 00" src="https://user-images.githubusercontent.com/70099457/158520325-59b13e50-0e79-4c30-9fd8-bf35c9bd580a.png">

**Comment by nlharris** [comment]
awesome, thanks!! how'd you fix it?

**Comment by nlharris** [comment]
i'd love to hear what you did to fix this issue (please email me) so i can fix it myself if it ever happens again!

**Comment by hzahroh** [comment]
Sure, Nomi. Sorry for my late reply.
First, go to all posts 
![image](https://user-images.githubusercontent.com/70099457/163793129-a4704952-91a1-40be-b2f9-b39179e7986f.png)
Then, choose quick edit. Please make sure to fill date and time
![image](https://user-images.githubusercontent.com/70099457/163793233-231d661b-6133-4e36-a2ab-e344b0b6c431.png)
Then, go to categories to ensure the post goes to the right category. In our case before, it's better to not checklist all of this
![image](https://user-images.githubusercontent.com/70099457/163793493-9c8e4370-67c3-4625-b413-6dbffaee4755.png)
Because it was checked, it went to "home". 
Hope this helps
