### ISSUE TITLE
Some blog posts not showing dates on open-bio.org/blog

### ISSUE THREAD

**Issue by nlharris** [OBF/homepage#74]
possibly related to #73?
![Screen Shot 2022-03-15 at 10 09 20 PM](https://user-images.githubusercontent.com/348704/158520874-20ed3eba-6394-4ff2-99ec-a952e20c6c30.png)

**Comment by Hrittik20** [comment]
Hi @nlharris, can you tell me where I can find the blog file?

**Comment by yochannah** [comment]
Hey Hrittik - what do you mean by the blog file? Wordpress is based on a php/mysql setup so posts are all stored in the database.

**Comment by yochannah** [comment]
actually, you probably mean just which page to edit, right? I _think_ it's this one. https://github.com/OBF/homepage/blob/14e698d2a5f09d762f2599941d21e40f7af0399f/home.php

**Comment by erik-whiting** [comment]
Hello, I am pretty sure I know how to fix this but have a quick question about setup.

I've Dockerized the app and have the WP instance running locally in a container but I can't get beyond **Step 5** in the `README.md`. When I click the link "Import WP Migration" I just see this:

![image](https://user-images.githubusercontent.com/47164199/163908380-7c8b3f1e-444e-409c-81cc-6922b8e344d0.png)

There's no "Basic" version for me to download and then import. I'm assuming this is something like seed data for the blog?

Anyway, I'm 99% sure that calls to `the_date()` need to be changed to `get_the_date("F j, Y")` because according to [this answer](https://wordpress.stackexchange.com/a/52497), this is a well known issue with `the_date` because it won't say the same date more than once (so if two articles are posted on the same day, only the first one will have the date, the second wont'). [I made a PR](https://github.com/OBF/homepage/pull/78) implementing this fix, but I can't know for sure if it works until I get the site  running locally (or someone with a local instance tests my branch).

**Comment by erik-whiting** [comment]
Howdy @nlharris and @yochannah, just wanted to ping y'all again and bring your attention to [this possible fix](https://github.com/OBF/homepage/pull/78). Let me know if there's anything I can clarify or take care of for you.

**Comment by nlharris** [comment]
Hey, sorry, I have no idea. Maybe @hzahroh would know?

**Comment by erik-whiting** [comment]
Hello again @nlharris and @yochannah . Through the magic of Docker and general hackery, I was able to fake my way through enough of the setup to actually test my PR. I can confirm that [this pull request](https://github.com/OBF/homepage/pull/78) fixes the problem in this issue. Let me know if there's anything you'd like me to change!

**Comment by hlapp** [comment]
Turns out that for some reason this didn't yet fix the issue, see https://github.com/OBF/homepage/pull/78#issuecomment-1191957008

**Comment by erik-whiting** [comment]
@hlapp this looks like it's working now. Can you double check the news page and confirm you see what I see (working dates)?

**Comment by nlharris** [comment]
Yes, it seems to be working now! Thanks so much for your help, @erik-whiting!
